export { default as H1 } from "./h1"
export { default as H2 } from "./h2"
export { default as H3 } from "./h3"
export { default as P } from "./p"
export { default as A } from "./a"
export { default as Link } from "./link"
